site_name: smkent's 3D printing guide with the Sovol SV06 Plus
site_url: https://3d.smkent.net
repo_name: smkent/3d
repo_url: https://github.com/smkent/3d

theme:
  name: material
  icon:
    logo: material/printer-3d-nozzle
  favicon: img/favicon.ico
  features:
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: yellow
      toggle:
        name: Switch to light mode
        icon: material/lightbulb-outline
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        name: Switch to dark mode
        icon: material/lightbulb

nav:
  - Getting Started:
    - getting-started/index.md
    - Background and Safety: getting-started/background-and-safety.md
    - Printer setup: getting-started/printer-setup.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  social:
    - name: bulbasaur0 on Printables
      link: https://www.printables.com/@bulbasaur0_1139994
      icon: simple/printables
    - name: bulbasaur0 on Thingiverse
      link: https://www.thingiverse.com/bulbasaur0/makes
      icon: simple/thingiverse
    - name: smkent on GitHub
      link: https://github.com/smkent
      icon: fontawesome/brands/github

plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
  - search
