site_name: 3D Printing & Sovol SV06 Plus
site_url: https://3d.smkent.net
repo_name: smkent/3d
repo_url: https://github.com/smkent/3d
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/printer-3d-nozzle
  favicon: img/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: yellow
      toggle:
        name: Switch to dark mode
        icon: material/lightbulb-outline
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep purple
      toggle:
        name: Switch to system preference for light/dark mode
        icon: material/lightbulb

nav:
  - Home: index.md
  - Getting Started:
    - getting-started/index.md
    - Background and safety: getting-started/background-and-safety.md
    - Printer assembly: getting-started/printer-assembly.md
    - Printer calibration: getting-started/printer-calibration.md
    - Slicer installation: getting-started/slicer-installation.md
    - Slicer configuration wizard: getting-started/slicer-configuration.md
    - Slicer tuning: getting-started/slicer-tuning.md
    - Prepare model: getting-started/prepare-model.md
    - Load filament: getting-started/load-filament.md
    - Print!: getting-started/print.md
    - Share your make: getting-started/publish-make.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences

extra_css:
  - css/custom.css

extra:
  social:
    - name: bulbasaur0 on Printables
      link: https://www.printables.com/@bulbasaur0_1139994
      icon: simple/printables
    - name: bulbasaur0 on Thingiverse
      link: https://www.thingiverse.com/bulbasaur0/makes
      icon: simple/thingiverse
    - name: smkent on GitHub
      link: https://github.com/smkent
      icon: fontawesome/brands/github

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - glightbox:
      auto_caption: true
  - privacy
  - search
