site_name: 3D Printing with the Sovol SV06 Plus
site_url: https://3d.smkent.net
repo_name: smkent/3d
repo_url: https://github.com/smkent/3d
edit_uri: "edit/main/docs/"

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: logo
  favicon: img/favicon.png
  features:
    - content.action.edit
    - content.action.view
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: yellow
      toggle:
        name: Switch to dark mode
        icon: material/lightbulb-outline
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: deep purple
      toggle:
        name: Switch to system preference for light/dark mode
        icon: material/lightbulb

nav:
  - Home: index.md
  - First Print Guide:
    - first-print/index.md
    - Background and safety: first-print/background-and-safety.md
    - Printer assembly: first-print/printer-assembly.md
    - Printer calibration: first-print/printer-calibration.md
    - Slicer installation: first-print/slicer-installation.md
    - Slicer configuration wizard: first-print/slicer-configuration.md
    - Slicer tuning: first-print/slicer-tuning.md
    - Preparing a model: first-print/prepare-model.md
    - Loading filament: first-print/load-filament.md
    - Making your first print!: first-print/print.md
    - Sharing your make: first-print/publish-make.md
  - Printing Reference:
    - reference/index.md
    - reference/finding-models.md
    - reference/tools.md
  - Add-ons & Upgrades:
    - upgrades/index.md
    - upgrades/printable.md
  - External Resources:
    - external-resources/index.md

markdown_extensions:
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - css/custom.css

extra:
  social:
    - name: bulbasaur0 on Printables
      link: https://www.printables.com/@bulbasaur0
      icon: simple/printables
    - name: bulbasaur0 on Thingiverse
      link: https://www.thingiverse.com/bulbasaur0/makes
      icon: simple/thingiverse
    - name: smkent on GitHub
      link: https://github.com/smkent
      icon: fontawesome/brands/github

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - glightbox:
      auto_caption: true
  - privacy
  - search
